### ISSUE TITLE
Support TLS connections

### ISSUE THREAD

**Issue by jonatanklosko** [livebook-dev/kino_db#10]
We need a checkbox for both Postgres and MySQL to enable TLS. When checked, we add `ssl: true, ssl_opts: [...]` to connection options. We can depend on CAStore for getting the certfile.

**Comment by josevalim** [comment]
We can likely require Erlang/OTP 25 in Livebook soon, which means we can depend on the machine cert store (which is now available in OTP).

**Comment by wojtekmach** [comment]
I think :castore package still has value in deployments where we are on OTP 25 but we don’t have os certs. An example is Hex provided Elixir/Erlang Docker images, we keep them minimal. So personally I think it would be nice if we use OS certs if available, CAStore if available, otherwise a good error message to install OS certs or :castore.

wdyt?

**Comment by josevalim** [comment]
It is probably worth discussing this with the Mint team, because the OS certificates may not be up to date either? I think priority should be castore > os > raise.

**Comment by wojtekmach** [comment]
Good point, I'll open up an issue.

**Comment by george-bitdotio** [comment]
I've also added a feature request for this in discussions here: https://github.com/livebook-dev/livebook/discussions/1722

**Comment by josevalim** [comment]
A pull request is welcome!

**Comment by hugobarauna** [comment]
@jonatanklosko is this one closed by https://github.com/livebook-dev/kino_db/pull/60 ?
